### ISSUE TITLE
1.4 OS please..

### ISSUE THREAD

**Issue by ahmadkeren** [keitarogg/HSR-Download-Library#16]

**Comment by ahmadkeren** [comment]
solved:
https://autopatchos.starrails.com/client/hkrpg_global/35/game_1.3.0_1.4.0_hdiff_anBAclTh9gfx7Lu6.zip

**Comment by keitarogg** [comment]
now there will be no more issues like this because of:

https://github.com/keitarogg/HSR-Download-Library/blob/master/PROD/CN/Latest.md

https://github.com/keitarogg/HSR-Download-Library/blob/master/PROD/OS/Latest.md
