### ISSUE TITLE
1.2版本更新

### ISSUE THREAD

**Issue by rainbowwarmth** [keitarogg/HSR-Download-Library#4]
前言：由于没有安卓版本所以你写一下吧，懒得再提供PR了，要合并来合并去，我提供CN的链接
游戏本体：https://autopatchcn.bhsr.com/client/cn/20230709224719_3CcrEpEKT9iaObJh/StarRail_1.2.0.zip
game_1.1.0_1.2.0_hdiff：https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_1.1.0_1.2.0_hdiff_HfBvygO7Z9aNPUmR.zip
game_1.0.5_1.2.0_hdiff：https://autopatchcn.bhsr.com/client/hkrpg_cn/33/game_1.0.5_1.2.0_hdiff_7qUejt4fMExIlrQp.zip
游戏启动器: https://autopatchcn.bhsr.com/client/cn/20230704200447_tSgyx751iAC1a5GZ/StarRail_setup_gw_20230717.exe

**Comment by rainbowwarmth** [comment]
@keitarogg 记得整理以下，弄好了关闭这个issues

**Comment by Hiro420** [comment]
FOR OS
full: https://autopatchos.starrails.com/client/download/20230710105424_73M0QhfClo2h6mt9/StarRail_1.2.0.zip
game_1.1.0_1.2.0_hdiff: https://autopatchos.starrails.com/client/hkrpg_global/35/game_1.1.0_1.2.0_hdiff_SJqF73LhiQrsv2cU.zip
game_1.0.5_1.2.0_hdiff: https://autopatchos.starrails.com/client/hkrpg_global/35/game_1.0.5_1.2.0_hdiff_R9c5WrVJ6PZqAhQ1.zip

**Comment by keitarogg** [comment]
who said that there is no android version 
![Screenshot_20230717_173724_com miHoYo hkrpg](https://github.com/keitarogg/HSR-Download-Library/assets/98975277/3a782ccc-6283-44b9-a40d-ba833413fdee)

**Comment by rainbowwarmth** [comment]
这个安装包哪来的🤔







                       
原始邮件
                       
                     

发件人："KEITARO"< ***@***.*** &gt;;

发件时间：2023/7/17 22:38

收件人："keitarogg/HSR-Download-Library"< ***@***.*** &gt;;

抄送人："rainbow"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [keitarogg/HSR-Download-Library] 1.2版本更新 (Issue #4)




 
who said that there is no android version

**Comment by keitarogg** [comment]
🤫
